# Generated by Django 2.0.6 on 2023-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver_driverinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('license_number', models.CharField(max_length=20, verbose_name='驾驶证编号')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('driving_experience', models.IntegerField(verbose_name='驾龄')),
                ('phone_number', models.CharField(max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('fatigue_driving_count', models.IntegerField(verbose_name='疲劳驾驶次数')),
                ('dangerous_driving_count', models.IntegerField(verbose_name='危险驾驶次数')),
                ('front_collision_warning_count', models.IntegerField(verbose_name='前车碰撞预警次数')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '驾驶员表',
                'verbose_name_plural': '驾驶员表',
            },
        ),
    ]
