# Generated by Django 2.0.6 on 2023-05-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='driver_driverinfo',
            new_name='DriverInfo',
        ),
    ]
