# Generated by Django 2.0.6 on 2023-05-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20230513_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverinfo',
            name='photo',
            field=models.CharField(default='', max_length=255, verbose_name='人脸识别照片'),
        ),
    ]
