# Generated by Django 2.0.6 on 2023-05-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_remove_messageinfo_rec_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageinfo',
            name='add_time',
            field=models.DateTimeField(verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='messageinfo',
            name='update_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='messagereplayinfo',
            name='add_time',
            field=models.DateTimeField(verbose_name='添加时间'),
        ),
    ]
