# Generated by Django 2.0.6 on 2023-05-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0002_auto_20230513_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='carmanage_carmanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='车牌号')),
                ('terminal_number', models.CharField(max_length=20, unique=True, verbose_name='车载终端编号')),
                ('operating_route', models.CharField(max_length=100, verbose_name='运营路线')),
                ('company', models.CharField(max_length=100, verbose_name='所属公司')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.DriverInfo')),
            ],
            options={
                'verbose_name': '车辆及终端表',
                'verbose_name_plural': '车辆及终端表',
            },
        ),
    ]
