# Generated by Django 2.0.6 on 2023-05-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20230513_1628'),
        ('carmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='carmanage_carmanage',
            new_name='Carmanage',
        ),
    ]
