# Generated by Django 2.0.6 on 2023-05-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_terminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTerminalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=30, verbose_name='车牌号')),
                ('fatigue_driving', models.IntegerField(verbose_name='疲劳驾驶次数')),
                ('dangerous_driving', models.IntegerField(verbose_name='危险驾驶次数')),
                ('front_collision', models.IntegerField(verbose_name='前车碰撞预警次数')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '车辆终端表',
                'verbose_name_plural': '车辆终端表',
            },
        ),
        migrations.DeleteModel(
            name='auto_terminal_autoterminalinfo',
        ),
    ]
