# Generated by Django 2.0.6 on 2023-05-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_terminal', '0002_auto_20230513_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoterminalinfo',
            name='car_owner',
            field=models.CharField(default='', max_length=30, verbose_name='驾驶员'),
        ),
    ]
