# Generated by Django 2.0.6 on 2023-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_terminal', '0003_autoterminalinfo_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoterminalinfo',
            name='add_time',
            field=models.DateField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
